IP-182 | Initial commit
medlypharmacy/testing-service pull request #1
Opened 2021-10-04 07:36 UTC by Pradnya-glitch

2021-10-04 10:33 UTC, vitulrana commented on infra/serverless.yml
> +service: testing-app
It should be `service: testingService`

2021-10-04 10:33 UTC, vitulrana commented on infra/serverless.yml
> +  testingApiEnv:  ${ssm:/aws/reference/secretsmanager/testingApiEnv~true}
I don't think we need to create secret as of now.

2021-10-04 10:34 UTC, vitulrana commented on infra/serverless.yml
> +                  cors: true
```suggestion
        events:
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: true
```

2021-10-05 05:32 UTC, vitulrana requested changes
@Pradnya-glitch App does not have Okta Setup as of now but Backend Service is using Okta Setup. Should we remove Authorization stuff from here ?

2021-10-05 05:35 UTC, Pradnya-glitch commented
> @Pradnya-glitch App does not have Okta Setup as of now but Backend Service is using Okta Setup. Should we remove Authorization stuff from here ?

Going ahead we might add it in app..as we want to use it for complete testing

2021-10-06 05:43 UTC, vitulrana approved these changes

2021-10-06 11:07 UTC, merged

2021-10-08 10:27 UTC, niraj8 commented on .github/workflows/build.yaml
> +                  path: dist
This step is not needed, please remove this